FROM node:18.17.1-alpine3.17

WORKDIR /app

RUN apk update && apk upgrade
RUN apk add git

COPY ./package*.json /app/

RUN npm install && npm cache clean --force

ADD . /app

RUN apk add openssl1.1-compat
RUN npx prisma db push

COPY . .

ENV PATH ./node_modules/.bin/:$PATH