version: "3"

services:
  hivemind-demo-dev:
    container_name: hivemind-demo-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    #    volumes:
    #      - .:/app
    #      - /app/node_modules
    ports:
      - "3000:3000"
      - "3001:3001"
