version: "3"

services:
  hivemind-demo:
    container_name: hivemind-demo
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - WS_PORT=3000
    ports:
      - "3000:3000"
      - "3001:3001"
