FROM node:18.12.1

WORKDIR /app

RUN apt-get update && apt-get install -y openssl libssl-dev

COPY ./package*.json /app/

RUN npm install && npm cache clean --force

ADD . /app

RUN npx prisma generate

COPY . .

ENV PATH ./node_modules/.bin/:$PATH

CMD ["npm", "run", "dev"]
